/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type AmbulancesAPI struct {
}

// Post /api/ambulance
// Saves new ambulance definition 
func (api *AmbulancesAPI) CreateAmbulance(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/ambulance/:ambulanceId
// Deletes specific ambulance 
func (api *AmbulancesAPI) DeleteAmbulance(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

