/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type AmbulanceWaitingListAPI struct {
}

// Post /api/waiting-list/:ambulanceId/entries
// Saves new entry into waiting list 
func (api *AmbulanceWaitingListAPI) CreateWaitingListEntry(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/waiting-list/:ambulanceId/entries/:entryId
// Deletes specific entry 
func (api *AmbulanceWaitingListAPI) DeleteWaitingListEntry(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/waiting-list/:ambulanceId/entries
// Provides the ambulance waiting list 
func (api *AmbulanceWaitingListAPI) GetWaitingListEntries(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/waiting-list/:ambulanceId/entries/:entryId
// Provides details about waiting list entry 
func (api *AmbulanceWaitingListAPI) GetWaitingListEntry(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/waiting-list/:ambulanceId/entries/:entryId
// Updates specific entry 
func (api *AmbulanceWaitingListAPI) UpdateWaitingListEntry(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

